weather.api.key=584d77f03c9a4536a8122118260707
weather.api.url=http://api.weatherapi.com/v1
climalert.ubicacion.objetivo=CABA

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mpeschel@frba.utn.edu.ar

spring.mail.password=cjmc kqdl igwl skap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true