weather.api.key=CLAVE_AQUI
weather.api.url=http://api.weatherapi.com/v1
climalert.ubicacion.objetivo=CABA

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=USUARIO_AQUI

spring.mail.password=PASSWORD_AQUI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true